# Metadata for your course

title: My first course
tagline: Learn how to write a course
description: Learn how to author your own course with only 16 steps.

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: my-lab-repo
  repo: lab-starter-template

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: createIssue
  title: Welcome
  body: welcome-text.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title: Create a new Pull Request
  description: Merge your Pull Request in the README.md file from Branch: (Branch name) to your Branch: master in your new Pull Request
  event: pull_request.opened
  actions:
  - type: gate, full list at https://lab.github.com/docs/actions
    left: '%payload.pull_request.title%'
    operator: ===
    right: Merge README
  - type: respond
    with: pull_request-opened.md
  #
  # - type:
  #   option:
