# Metadata for your course

title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: # the name of the repository when it is created for the learner
  repo: # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: createIssue
  title: Welcome
  body: welcome-text.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title: Create a new Pull Request
  description: Merge your Pull Request in the README.md file from Branch: (Branch name) to your Branch: master in your new Pull Request
  event: pull_request.opened
  actions:
  - type: gate, full list at https://lab.github.com/docs/actions
                  # some actions require additional options, those should appear below `type:`
    operator: ===
    right: Merge README
  - type: respond
  #   option:
  #
  # - type:
  #   option:
